### PR TITLE
Database setup

### PR DESCRIPTION
**Pull request by jennl97**
# Description

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Change Status

- [ ] Complete, tested, ready to review and merge
- [ ] Complete, but not tested (may need new tests)
- [ ] Incomplete/work-in-progress, PR is for discussion/feedback

# How Has This Been Tested?

- [ ] Test A
- [ ] Test B

# Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] My code has been reviewed by at least one peer
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] There are no merge conflicts

### CODE REVIEW

**Review by LiamColeE — COMMENTED** [review]
Everything looks good to go.

**Review by deegrams221 — CHANGES_REQUESTED** [review]
Remember to put the .env in the .gitignore, we don't want the USER and PASSWORD available to the public

**Review by jennl97 — COMMENTED** [review]
changed gitignore

**Comment by carlpadilla** [comment]
Code looks clean easy to read.

From what I can tell it all looks good.

**Review by carlpadilla — COMMENTED** [review]
Code looks clean easy to read.

From what I can tell it all looks good.

Best practices are being used.

**Comment by jennl97** [comment]
Updated code

**Review by deegrams221 — APPROVED** [review]

**Pull request merged**
